- name: Check if deployment directory exists
  stat:
    path: "{{ component_path }}"
  register: component_path_exists

- name: Create backup of existing deployment
  block:
    - name: Create timestamped backup directory
      file:
        path: "{{ component_path }}/deployments/{{ _date }}"
        state: directory
        mode: '0755'

    - name: Find all deployment files to backup
      find:
        paths: "{{ component_path }}"
        file_type: any
        excludes: ["deployments"]
      register: files_to_move

    - name: Move current deployment files to backup
      command: >
        mv "{{ item.path }}" "{{ component_path }}/deployments/{{ _date }}/"
      loop: "{{ files_to_move.files }}"
      when: files_to_move.matched > 0

    - name: Compress backup directory to tar.gz
      archive:
        path: "{{ component_path }}/deployments/{{ _date }}"
        dest: "{{ component_path }}/deployments/{{ _date }}.tar.gz"
        format: gz

    - name: Remove uncompressed backup directory
      file:
        path: "{{ component_path }}/deployments/{{ _date }}"
        state: absent
  when: component_path_exists.stat.exists
