---
- name: Copy application tarball to server
  copy:
    src: "../app.tar.gz"
    dest: "{{ component_path }}/"

- name: Extract application tarball
  ansible.builtin.unarchive:
    src: "{{ component_path }}/app.tar.gz"
    dest: "{{ component_path }}/"
    remote_src: yes

- name: Find all extracted application files
  ansible.builtin.find:
    paths: "{{ component_path }}/app"
    file_type: any 
    recurse: yes
    hidden: yes
  register: found_items

- name: Deploy application files to target directory
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "{{ component_path }}/{{ item.path | regex_replace('^.*/app/', '') }}"
    remote_src: yes
  loop: "{{ found_items.files }}"
  loop_control:
    label: "{{ item.path | basename }}" 

- name: Clean up temporary extraction files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ component_path }}/app"
    - "{{ component_path }}/app.tar.gz"
